In [1]:
import numpy as np
import  pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
train = pd.read_csv('train.csv')
train.head()

ID_code  target    var_0   var_1    var_2   var_3    var_4   var_5   var_6  \
0  train_0       0   8.9255 -6.7863  11.9081  5.0930  11.4607 -9.2834  5.1187   
1  train_1       0  11.5006 -4.1473  13.8588  5.3890  12.3622  7.0433  5.6208   
2  train_2       0   8.6093 -2.7457  12.0805  7.8928  10.5825 -9.0837  6.9427   
3  train_3       0  11.0604 -2.1518   8.9522  7.1957  12.5846 -1.8361  5.8428   
4  train_4       0   9.8369 -1.4834  12.8746  6.6375  12.2772  2.4486  5.9405   

     var_7   ...     var_190  var_191  var_192  var_193  var_194  var_195  \
0  18.6266   ...      4.4354   3.9642   3.1364   1.6910  18.5227  -2.3978   
1  16.5338   ...      7.6421   7.7214   2.5837  10.9516  15.4305   2.0339   
2  14.6155   ...      2.9057   9.7905   1.6704   1.6858  21.6042   3.1417   
3  14.9250   ...      4.4666   4.7433   0.7178   1.4214  23.0347  -1.2706   
4  19.2514   ...     -1.4905   9.5214  -0.1508   9.1942  13.2876  -1.5121   

   var_196  var_197  var_198  var_199  
0   7.8784   8.5635  12.7803  -1.0914  
1   8.1267   8.7889  18.3560   1.9518  
2  -6.5213   8.2675  14.7222   0.3965  
3  -2.9275  10.2922  17.9697  -8.9996  
4   3.9267   9.5031  17.9974  -8.8104  

[5 rows x 202 columns]

In [4]:
x = train.drop(['ID_code','target'],axis = 1)
y = train['target']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)

In [12]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [13]:
lg.fit(x_train,y_train)

C:\Users\aswprabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [27]:
lg_predictions = lg.predict(x_test)

In [28]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,lg_predictions))
print("\n")
print(classification_report(y_test,lg_predictions))

[[53083   799]
 [ 4504  1614]]


              precision    recall  f1-score   support

           0       0.92      0.99      0.95     53882
           1       0.67      0.26      0.38      6118

   micro avg       0.91      0.91      0.91     60000
   macro avg       0.80      0.62      0.67     60000
weighted avg       0.90      0.91      0.89     60000



In [29]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()

In [30]:
dtree.fit(x_train,y_train)
dtree_predictions = dtree.predict(x_test)

In [31]:
print(confusion_matrix(y_test,dtree_predictions))
print("/n")
print(classification_report(y_test,dtree_predictions))

[[48898  4984]
 [ 4858  1260]]
/n
              precision    recall  f1-score   support

           0       0.91      0.91      0.91     53882
           1       0.20      0.21      0.20      6118

   micro avg       0.84      0.84      0.84     60000
   macro avg       0.56      0.56      0.56     60000
weighted avg       0.84      0.84      0.84     60000



In [32]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)

In [33]:
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [34]:
rf_predictions = rf.predict(x_test)

In [35]:
print(confusion_matrix(y_test,rf_predictions))
print("/n")
print(classification_report(y_test,rf_predictions))

[[53882     0]
 [ 6117     1]]
/n
              precision    recall  f1-score   support

           0       0.90      1.00      0.95     53882
           1       1.00      0.00      0.00      6118

   micro avg       0.90      0.90      0.90     60000
   macro avg       0.95      0.50      0.47     60000
weighted avg       0.91      0.90      0.85     60000



In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [37]:
sc.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [38]:
scaled_x = sc.transform(x)

In [41]:
x_collumns = x_train.columns
scaled_x_df = pd.DataFrame(scaled_x,index=None,columns=x_collumns)

In [45]:
from sklearn.decomposition import PCA
pca = PCA(n_components=10)

In [46]:
pca.fit(scaled_x)
pca_transformed = pca.transform(scaled_x)

In [61]:
scaled_PCA_tranformed_df = pd.DataFrame(pca_transformed,index=None)

In [62]:
X_train,X_test,Y_train,Y_test = train_test_split(scaled_PCA_tranformed_df,y,test_size = 0.30)

In [64]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=600)
rf.fit(X_train,Y_train)
rf_predictions = rf.predict(X_test)
print(confusion_matrix(Y_test,rf_predictions))
print("/n")
print(classification_report(Y_test,rf_predictions))

[[53258   654]
 [ 4874  1214]]
/n
              precision    recall  f1-score   support

           0       0.92      0.99      0.95     53912
           1       0.65      0.20      0.31      6088

   micro avg       0.91      0.91      0.91     60000
   macro avg       0.78      0.59      0.63     60000
weighted avg       0.89      0.91      0.89     60000

